# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/oms/VideoControlIP/ip_repo/image_capture_manger/image_capture_manger.cache/wt [current_project]
set_property parent.project_path E:/oms/VideoControlIP/ip_repo/image_capture_manger/image_capture_manger.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/oms/VideoControlIP/ip_repo/image_capture_manger/src/imageCaptureManager_v1_0_S00_AXI.v
  E:/oms/VideoControlIP/ip_repo/image_capture_manger/src/imageCaptureManager_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top image_capture_manager_v1_0 -part xc7z020clg400-2


write_checkpoint -force -noxdef image_capture_manager_v1_0.dcp

catch { report_utilization -file image_capture_manager_v1_0_utilization_synth.rpt -pb image_capture_manager_v1_0_utilization_synth.pb }
