# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/oms/VideoControlIP/ip_repo/imageCaptureManager/edit_imageCaptureManager_v1_0.cache/wt [current_project]
set_property parent.project_path E:/oms/VideoControlIP/ip_repo/imageCaptureManager/edit_imageCaptureManager_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/oms/VideoControlIP/ip_repo/imageCaptureManager [current_project]
read_verilog -library xil_defaultlib {
  E:/oms/VideoControlIP/ip_repo/imageCaptureManager/imageCaptureManager_1.0/hdl/imageCaptureManager_v1_0_S00_AXI.v
  E:/oms/VideoControlIP/ip_repo/imageCaptureManager/imageCaptureManager_1.0/hdl/imageCaptureManager_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top imageCaptureManager_v1_0 -part xc7z020clg400-3


write_checkpoint -force -noxdef imageCaptureManager_v1_0.dcp

catch { report_utilization -file imageCaptureManager_v1_0_utilization_synth.rpt -pb imageCaptureManager_v1_0_utilization_synth.pb }
